@base_url = http://localhost:3000
# http://localhost:3000
# http://165.22.49.116:3000
# http://s1.azizfath.com:3000
@accessToken = {{signin.response.body.data.accessToken}}
GET {{base_url}}/
###
POST {{base_url}}/admin/create-user HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json

{
    "name": "Admin1",
    "email": "admin1@gmail.com",
    "password": "12345678",
    "noHp": "0811111156"
}
###
# @name signin
POST {{base_url}}/auth/signin HTTP/1.1
content-type: application/json
 
{ 
    "email": "admin1@gmail.com",
    "password": "12345678"
}
###
GET {{base_url}}/auth/me HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json

###
POST {{base_url}}/admin/create-agent HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json

{
    "name": "Dummy2",
    "noHp": "081111111111",
    "rfid": "36775"
}
###
DELETE {{base_url}}/admin/delete-agent?agentid=655259a8f04cbd76e59cd30e HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json
###
POST {{base_url}}/admin/edit-agent?agentid=65c30541198b7f524f13ef1f HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json

{
    "name" : "Juki",
    "noHp" : "0814343434"
}
###
POST {{base_url}}/command/register-door HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json

{
    "doorNumber": "5.4.2"
}
###
DELETE {{base_url}}/command/delete-door?doorid=656ea7e97e75c11986628e22 HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json
###
POST {{base_url}}/command/toggle-door-status?doorNumber=5.4.1&status=close&statusBool=0 HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json
###
GET {{base_url}}/info/get-doors
Authorization: Bearer {{accessToken}}
Content-Type: application/application/json
###
GET {{base_url}}/info/get-agents
Authorization: Bearer {{accessToken}}
Content-Type: application/application/json
###
GET {{base_url}}/info/get-door-logs?doorNumber=5.4.1&page=1
Authorization: Bearer {{accessToken}}
Content-Type: application/application/json

