@base_url = http://localhost:3000
# http://localhost:3000
# https://165.22.49.116:3000
@accessToken = {{signin.response.body.data.accessToken}}
GET {{base_url}}/
###
POST {{base_url}}/admin/create-user HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json

{
    "name": "Admin1",
    "email": "admin1@gmail.com",
    "password": "12345678",
    "noHp": "0811111156"
}
###
# @name signin
POST {{base_url}}/auth/signin HTTP/1.1
content-type: application/json
 
{ 
    "email": "admin1@gmail.com",
    "password": "12345678"
}
###
POST {{base_url}}/admin/create-agent HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json

{
    "name": "Dummy2",
    "noHp": "081111111111",
    "rfid": "36775"
}
###
POST {{base_url}}/command/register-door HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json

{
    "doorNumber": "5.4.1"
}
###
POST {{base_url}}/command/toggle-door-status?doorNumber=5.4.1&status=open&statusBool=1 HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: application/json
